version: "3.7"
services:
  app:
    build:
      args:
        user: porthos
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: alopeyk-image
    container_name: alopeyk-container
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - alopeyk-notifications
  nginx:
    image: nginx:alpine
    container_name: nginx-alopeyk
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - alopeyk-notifications
  redis:
    image: redis:latest
    container_name: redis-alopeyk
    restart: unless-stopped
    networks:
      - alopeyk-notifications
networks:
  alopeyk-notifications:
    driver: bridge
